### ISSUE TITLE
Security review needed

### ISSUE THREAD

**Issue by amiller** [amiller/ethereum-blockhashes#1]
- I'm uncertain about this `~calldataload` stuff. Is it guaranteed to work consistently? Or might the offsets be different depending on e.g. the size of the header, the current block number, etc.?
- For comparing `sha3(header)` to the hash of a known block, I had to use the odd phrase `h - p == 0`, since direct comparison didn't seem to work. Does subtraction even work mod 32 bytes as I intend?
- Is there any way to cause `sha3` to return `0` e.g. if the string is empty or too long? I don't check for this case, but if it can happen, might cause invalid data to be recorded.

**Comment by ethers** [comment]
Hi,

Looks like with latest commit https://github.com/amiller/ethereum-blockhashes/commit/e5e81f28534c16d5eb3a424484d59887ea12a2e7 the first 2 questions are avoided.  The simplification is clearer, though IIRC `calldataload` uses less gas than `slice`
 (tradeoff between optimization and clarity).  Also, `extract` function was added but not currently used.

`calldataload` offsets will be different if the header size is different (and probably if the arguments to the function `add_old` are changed/added/reordered)
The reference for the `calldataload` data is https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI

With sha3, at the EVM-level `sha3` won't return `0` (unless the actual message that leads to Keccak digest of 0 is used)
Here's a test on sha3 of "empty":
https://github.com/ethereum/tests/blob/7fb4c07a8ca604980083b41ee0ef5d87c1c386ed/VMTests/vmSha3Test.json#L2
`sha3` will cause out of gas exception if string is too long, and this looks like the test:
https://github.com/ethereum/tests/blob/7fb4c07a8ca604980083b41ee0ef5d87c1c386ed/VMTests/vmSha3Test.json#L327
